---
- name: First Play
  hosts: Tulsa_Test
  gather_facts: True
  connection:  local
  tasks:
   - name: Fist Task
     ios_command:
         commands: show version
   - name: Second Tack
     ios_command:
         commands: show inventory
     register: version
