---
- name: First Play
  hosts: Tulsa_Test
  gather_facts: False
  connection:  local
  tasks:
   - name: Fist Task
     ios_command:
         commands: telnet 172.18.200.170
         commands: show version
     register: version
