---
- hosts: AnsibleTest
  gather_facts: no
  tasks:
  - name: Backup Running Config  
     ios_command:
       commands: show run  
     register: config
  - name: Save config to local file
    copy:
      content: "{{ config_result.config }}"
      dest: "/network-programmability/backups/{{ inventory_hostname }}_running_config.txt"
