---
- hosts: cisco
  gather_facts: no
  tasks:
  - name: Save Cisco running config to server
    ios_config:
      save: yes
    register: config_result
  - name: Save config to local file
    copy:
      content: "{{ config_result.config }}"
      dest: "configs/{{ inventory_hostname }}_running_config.txt"
