---
- name: First Play
  hosts: Tulsa_Test
  gather_facts: True
  connection:  local
  tasks:
    - name: copying file with playbook
      become: true 
      copy:
        scp ~/network-programmability/images/c2960x-universalk9-mz admin@172.18.200.170:flash/
