---
- hosts: Tulsa_Switch
  gather_facts: true
  become: yes

  tasks:
  - name: Show Running Configuration
    ios_command:
      commands:
        - show run
    register: config
    
  - name: Save output to /etc/ansible/backups
    copy:
     content: "{{ config.stdout[0] }}"
     dest: "/etc/ansible/backups/show_run_config_{{ inventory_hostname }}.txt"
