---
- name: First Play
  hosts: Tulsa_Test
  gather_facts: False
  connection:  local
  tasks:
   - name: Fist Task
     ios_command:
         command: reload
                  prompt: '[confirm]'
                  answer: "\r"
     register: version
