---
- name: 
  hosts: Tulsa_Switch
  tasks:
  - name: Show Running Configuration
    ios_command:
      commands:
        - show run
    register: config
    
  - name: Save output to /etc/ansible/backups
    copy:
     content: "{{ config.stdout[0] }}"
