---
- name: First Play
  hosts: Tulsa_Test
  gather_facts: True
  connection:  local
  tasks:
  - name: Show Running Configuration
    ios_command:
      commands:
        - show run
    
  - name: Save output to /tmp/ansible/backups
    copy:
     content: "{{ config.stdout[0] }}"
