- name: IOS ROUTERS
  hosts: Tulsa_Test
  gather_facts: false
  connection: local

  tasks:
    - name: IOS CONFIG
      ios_command:
        commands: show run
      register: output_router

    - name: SAVE IOS CONFIG
      copy:
        content: "{{ output_router.stdout[0] }}"
        dest: "//172.18.200.195/tmp/backups//show_run_{{ inventory_hostname }}.txt"
