- name: IOS ROUTERS
  hosts: Tulsa_Test
  gather_facts: false
  connection: local

  tasks:
    - name: IOS CONFIG
      ios_command:
        commands: show run
      register: output_router

    - name: copy code
      debug:  	
        var: output_router
