---
# Ansible Playbook to upgrade Cisco IOS 

- name: Upgrade CISCO IOS 
  hosts: AnsibleTest
  gather_facts: True
  #connection:  network_cli
  
  vars: 
    upgrade_ios_version: 152-7.E6

  tasks:
    - name: CHECK CURRENT VERSION
      ios_facts:

    - debug: 
        msg: 
        - "Current version is {{ ansible_net_version }}"
        - "Upgrade image is c2960x-universalk9-mz.152-7.E6.bin"

    - debug: 
        msg: 
        - "Image is not compliant and will be upgraded"

      when: ansible_net_version != upgrade_ios_version

## Create backup folder for today 

- hosts: localhost

  tasks:
   - name: Get ansible date/time facts
     setup:
       filter: "ansible_date_time"
       gather_subset: "!all"

   - name: Store DTG as fact
     set_fact:
       DTG: "{{ ansible_date_time.date }}"

   - name: Create Directory {{hostvars.localhost}}
     file:
       path: /network-programmability/backups/{{hostvars.localhost}}
       state: directory
     run_once: true

## Backup Running Config 

- hosts: AnsibleTest

  tasks:
   - name: Backup Running Config  
     ios_command:
       commands: show run  
     register: config

   - name: Save output to /network-programmability/backups/
     copy:
       content: "{{config.stdout[0]}}"
       dest: "/network-programmability/backups/{{hostvars.localhost}}/{{ inventory_hostname }}-{{hostvars.localhost}}-config.txt"

## SAVE the Running Config 

   - name: Save running config 
     ios_config:
       save_when: always 

## Copy software to target device 

   - name: Copy Image // This could take up to 4 minutes
     ios_config:
       commands:
         - "scp /network-programmability/images/c2960x-universalk9-mz admin@172.18.200.170:flash/"
     #net_put: 
       #src: "/network-programmability/images/c2960x-universalk9-mz.152-7.E6.bin"
       #dest: "flash:/c2960x-universalk9-mz.152-7.E6.bin"
     #vars: 
       #ansible_command_timeout: 600

## Change the Boot Variable to the new image 

   - name: Change Boot Variable to new image 
     ios_config: 
       commands: 
         - "boot system flash:c2960x-universalk9-mz.152-7.E6.bin"
       save_when: always 

## Reload the device 

   - name: Reload the Device 
     cli_command: 
       command: reload
       prompt: 
         - confirm
       answer: 
         - 'y'
         
## Wait for Reachability to the device 

   - name: Wait for device to come back online
     wait_for:
       host: "{{ inventory_hostname }}"
       port: 22
       delay: 90
     delegate_to: localhost

## Check current image 

   - name: Check Image Version      
     ios_facts:

   - debug: 
       msg: 
       - "Current version is {{ ansible_net_version }}"

   - name: ASSERT THAT THE IOS VERSION IS CORRECT
   
     vars: 
       upgrade_ios_version: 152-7.E6

     assert:
       that:
         - upgrade_ios_version == ansible_net_version
   - debug: 
       msg: 
       - "Software Upgrade has been completed"
