---
- name: First Play
  hosts: Tulsa_Test
  gather_facts: True
  connection:  local
  tasks:
    - name: copying file with playbook
      become: true 
      copy:
        src: "~/network-programmability/images/c2960-lanbasek9-mz.122-55.SE12.bin"
        dest: flash
