---
- name: Upgrade Cisco IOS code
  hosts: cisco
  gather_facts: no
  
  tasks:
    - name: Copy new code to device
      cisco_ios_scp:
      src: ~/network-programmability/images/c2960-lanbasek9-mz.122-55.SE12.bin
      dest: flash:/

    - name: Install new code
      cisco_ios_software:
      image: flash:/c2960-lanbasek9-mz.122-55.SE12.bin
      replace: yes
